### ISSUE TITLE
뭐 지금 중요한 건 아니지만

### ISSUE THREAD

**Issue by HurSungYun** [unbiarirang/face_detection_django#1]
https://github.com/unbiarirang/face_detection_django/blob/7e87d3863c13b19a0dc48319e6c78e2a9fc501d4/mysite/settings.py#L23

요런 secret 키를 커밋하는 건 굉장히 위험해요.

재밌는 거 하네요. 끝나고 보여줘요. ㅋㅋㅋㅋㅋ

**Comment by unbiarirang** [comment]
감사합니다 ㅎㅎ
생각해 보니까 face detection이 아니라 person detection 이었지만 ㅋㅋㅋㅋ 알겠습니다
